type Contato {
  id: Int
  name: String
  email: String
  phoneNumber: String 
}

input ContatoInput {
  name: String
  email: String
  phoneNumber: String 
}

input FiltroInput {
  id: Int
  email: String
}

type Query {
  contatos: [Contato]
}

type Mutation {
  criarContato(data: ContatoInput): Contato
  atualizarContato(id: Int!, data: ContatoInput): Contato
  deletarContato(filtro: FiltroInput): Boolean
}